// PairingSessionToken.swift — Phase 12.1
//
// Bootstrap payload encoded into the pairing QR code.
//
// Per 07_PROTOCOL_SPECIFICATION.md §QR Contents:
//   "The QR code should contain only the minimum information required
//    to bootstrap pairing."
//
// Included fields (per spec §QR Contents):
//   • Temporary pairing session identifier
//   • Protocol version
//   • Backend routing information (URL)
//   • Session expiration information
//
// Fields that MUST NEVER be included (per spec §QR Contents):
//   • Private keys
//   • Long-term authentication secrets
//   • Permanent trust information
//   • User notification data
//
// Phase 12.2 will:
//   - Replace backendUrl placeholder with the live relay endpoint
//   - Enforce single-use on the backend (§Single-Use Pairing)
//   - Destroy the session immediately after scan or expiry

import Foundation

/// Bootstrap payload encoded into the QR code shown during pairing.
/// Per 07_PROTOCOL_SPECIFICATION.md §QR Contents and
/// 04_SECURITY_MODEL.md §QR Code Lifetime.
struct PairingSessionToken: Codable, Sendable {

    /// Temporary, single-use UUID for this pairing session.
    /// Invalidated immediately after a successful scan or expiry.
    /// Per spec: "Once pairing completes or fails, the session is destroyed."
    let sessionId: String

    /// MacEcho protocol version for compatibility negotiation.
    let protocolVersion: Int

    /// WebSocket URL the Android client connects to after scanning.
    /// Placeholder in Phase 12.1. Phase 12.2 provides the live endpoint.
    let backendUrl: String

    /// Unix epoch milliseconds when this token expires.
    /// Per 04_SECURITY_MODEL.md §QR Code Lifetime:
    ///   "Every QR code generated by the macOS application must have a
    ///    short validity period."
    let expiresAt: Int64

    // -------------------------------------------------------------------------
    // Factory
    // -------------------------------------------------------------------------

    /// How long a generated token remains valid from the moment of creation.
    /// The spec mandates a "short validity period" without specifying a value.
    /// 5 minutes allows the user to scan comfortably while limiting exposure.
    static let lifetimeSeconds: TimeInterval = 300 // 5 minutes

    /// Creates a fresh, single-use token valid for `lifetimeSeconds`.
    /// Per 04_SECURITY_MODEL.md §Single-Use Pairing: only one active pairing
    /// QR code may exist at any given time.
    static func generate() -> PairingSessionToken {
        let expiryMs = Int64((Date().timeIntervalSince1970 + lifetimeSeconds) * 1_000)
        
        let resolvedBackendUrl: String
        
        // 1. Highest priority: Environment variable (works in Xcode or via Terminal launch)
        if let envUrl = ProcessInfo.processInfo.environment["MACECHO_BACKEND_URL"], !envUrl.isEmpty {
            resolvedBackendUrl = envUrl
        } else {
            #if DEBUG
            // 2. Development fallback: UserDefaults (works when double-clicked in Finder)
            // Can be updated via: defaults write com.macecho.app MACECHO_BACKEND_URL ws://<new-ip>:3000/ws
            let userDefaultsUrl = UserDefaults.standard.string(forKey: "MACECHO_BACKEND_URL")
            // 3. Development baseline: Local LAN IP (used if nothing else is set)
            resolvedBackendUrl = userDefaultsUrl ?? "ws://192.168.29.228:3000/ws"
            #else
            // 4. Production baseline
            resolvedBackendUrl = "wss://relay.macecho.app/ws"
            #endif
        }

        return PairingSessionToken(
            sessionId: UUID().uuidString,
            protocolVersion: 1,
            backendUrl: resolvedBackendUrl,
            expiresAt: expiryMs
        )
    }

    // -------------------------------------------------------------------------
    // Helpers
    // -------------------------------------------------------------------------

    /// Integer seconds remaining before expiry. Negative when already expired.
    var secondsRemaining: Int {
        let nowMs = Int64(Date().timeIntervalSince1970 * 1_000)
        return Int((expiresAt - nowMs) / 1_000)
    }

    /// True when this token has passed its expiry time.
    var isExpired: Bool { secondsRemaining <= 0 }

    /// JSON-encoded representation of this token for embedding in the QR image.
    /// Sorted keys produce a consistent byte sequence for reproducible QR codes.
    func jsonString() -> String? {
        let encoder = JSONEncoder()
        encoder.outputFormatting = .sortedKeys
        guard let data = try? encoder.encode(self) else { return nil }
        return String(data: data, encoding: .utf8)
    }
}
