// PairDeviceViewController.swift — Phase 12.1
//
// Pair Device page — displays a real QR code and waits for the Android device.
//
// Responsibilities:
//   • Generates a PairingSessionToken and encodes it as a QR image.
//   • Shows a countdown timer (5 min) and auto-regenerates the QR on expiry.
//   • Shows a spinning indicator and "Waiting…" status label.
//   • Provides a "Generate New Code" button for manual refresh.
//
// Per 06_UI_GUIDELINES.md §QR Pairing Interface:
//   "The pairing screen should clearly indicate Waiting for Android device,
//    Pairing in progress, Pairing successful, Pairing failed."
//
// Per 04_SECURITY_MODEL.md §QR Code Lifetime:
//   "Each QR code generated by the macOS application must have a short
//    validity period. Generating a new QR code immediately invalidates any
//    previously generated unused QR codes."
//
// Must NOT contain:
//   - Permanent device pairing  → Phase 12.3
//   - Trust establishment       → Phase 12.3
//   - Keystore/Keychain writes  → Phase 12.3

import AppKit

@MainActor
final class PairDeviceViewController: NSViewController, Navigable {

    // -------------------------------------------------------------------------
    // Navigable
    // -------------------------------------------------------------------------

    weak var navigationController: AppNavigationController?

    // -------------------------------------------------------------------------
    // Private state
    // -------------------------------------------------------------------------

    private var currentToken: PairingSessionToken?
    private var countdownTimer: Timer?
    private var pairingController: PairingHandshakeController?
    private var stateObservationTask: Task<Void, Never>?

    // Subview references
    private weak var qrImageView: NSImageView?
    private weak var countdownLabel: NSTextField?
    private weak var spinner: NSProgressIndicator?
    private weak var statusLabel: NSTextField?

    // -------------------------------------------------------------------------
    // Lifecycle
    // -------------------------------------------------------------------------

    override func loadView() {
        view = NSView()
    }

    override func viewDidLoad() {
        super.viewDidLoad()
        buildInterface()
    }

    override func viewDidAppear() {
        super.viewDidAppear()
        startNewPairingSession()
    }

    override func viewWillDisappear() {
        super.viewWillDisappear()
        stopTimer()
        stateObservationTask?.cancel()
        Task { await pairingController?.cancel(reason: "user_cancelled") }
    }

    // -------------------------------------------------------------------------
    // Interface Construction
    // -------------------------------------------------------------------------

    private func buildInterface() {
        // ── Navigation header ──────────────────────────────────────────────
        let header = makePageHeader(title: "Pair Device")
        header.translatesAutoresizingMaskIntoConstraints = false
        view.addSubview(header)

        let sep = makeSeparator()
        sep.translatesAutoresizingMaskIntoConstraints = false
        view.addSubview(sep)

        // ── QR container: white rounded rect ──────────────────────────────
        let qrContainer = NSView()
        qrContainer.wantsLayer = true
        qrContainer.layer?.backgroundColor = NSColor.white.cgColor
        qrContainer.layer?.cornerRadius = 14
        qrContainer.layer?.shadowColor = NSColor.black.cgColor
        qrContainer.layer?.shadowOpacity = 0.08
        qrContainer.layer?.shadowOffset = CGSize(width: 0, height: -2)
        qrContainer.layer?.shadowRadius = 10
        qrContainer.translatesAutoresizingMaskIntoConstraints = false

        let qrImageView = NSImageView()
        qrImageView.imageScaling = .scaleNone
        qrImageView.imageAlignment = .alignCenter
        qrImageView.translatesAutoresizingMaskIntoConstraints = false
        qrContainer.addSubview(qrImageView)
        self.qrImageView = qrImageView

        view.addSubview(qrContainer)

        // ── Instruction text ───────────────────────────────────────────────
        let instructionLabel = NSTextField(wrappingLabelWithString:
            "Point your Android camera at this code")
        instructionLabel.font = .systemFont(ofSize: 13, weight: .regular)
        instructionLabel.textColor = .secondaryLabelColor
        instructionLabel.alignment = .center
        instructionLabel.translatesAutoresizingMaskIntoConstraints = false
        view.addSubview(instructionLabel)

        // ── Spinner + status ───────────────────────────────────────────────
        let spinner = NSProgressIndicator()
        spinner.style = .spinning
        spinner.isIndeterminate = true
        spinner.controlSize = .small
        spinner.translatesAutoresizingMaskIntoConstraints = false
        view.addSubview(spinner)
        self.spinner = spinner

        let statusLabel = NSTextField(labelWithString: "Waiting for Android device…")
        statusLabel.font = .systemFont(ofSize: 12, weight: .regular)
        statusLabel.textColor = .secondaryLabelColor
        statusLabel.alignment = .center
        statusLabel.translatesAutoresizingMaskIntoConstraints = false
        view.addSubview(statusLabel)
        self.statusLabel = statusLabel

        // ── Countdown label ────────────────────────────────────────────────
        let countdownLabel = NSTextField(labelWithString: "Expires in 5:00")
        countdownLabel.font = .monospacedDigitSystemFont(ofSize: 12, weight: .regular)
        countdownLabel.textColor = .tertiaryLabelColor
        countdownLabel.alignment = .center
        countdownLabel.translatesAutoresizingMaskIntoConstraints = false
        view.addSubview(countdownLabel)
        self.countdownLabel = countdownLabel

        // ── Generate New Code button ───────────────────────────────────────
        let refreshBtn = NSButton(title: "Generate New Code", target: self,
                                  action: #selector(regenerateManually))
        refreshBtn.bezelStyle = .rounded
        refreshBtn.font = .systemFont(ofSize: 13, weight: .regular)
        refreshBtn.translatesAutoresizingMaskIntoConstraints = false
        view.addSubview(refreshBtn)

        // ── Constraints ────────────────────────────────────────────────────
        let qrSize: CGFloat = 190
        let pad: CGFloat = 14

        NSLayoutConstraint.activate([
            // Navigation header
            header.topAnchor.constraint(equalTo: view.topAnchor),
            header.leadingAnchor.constraint(equalTo: view.leadingAnchor),
            header.trailingAnchor.constraint(equalTo: view.trailingAnchor),
            header.heightAnchor.constraint(equalToConstant: 48),

            // Separator
            sep.topAnchor.constraint(equalTo: header.bottomAnchor),
            sep.leadingAnchor.constraint(equalTo: view.leadingAnchor),
            sep.trailingAnchor.constraint(equalTo: view.trailingAnchor),
            sep.heightAnchor.constraint(equalToConstant: 1),

            // QR container (white card, centred horizontally)
            qrContainer.topAnchor.constraint(equalTo: sep.bottomAnchor, constant: 22),
            qrContainer.centerXAnchor.constraint(equalTo: view.centerXAnchor),
            qrContainer.widthAnchor.constraint(equalToConstant: qrSize + pad * 2),
            qrContainer.heightAnchor.constraint(equalToConstant: qrSize + pad * 2),

            // QR image inside container with even padding
            qrImageView.centerXAnchor.constraint(equalTo: qrContainer.centerXAnchor),
            qrImageView.centerYAnchor.constraint(equalTo: qrContainer.centerYAnchor),
            qrImageView.widthAnchor.constraint(equalToConstant: qrSize),
            qrImageView.heightAnchor.constraint(equalToConstant: qrSize),

            // Instruction text
            instructionLabel.topAnchor.constraint(equalTo: qrContainer.bottomAnchor, constant: 16),
            instructionLabel.centerXAnchor.constraint(equalTo: view.centerXAnchor),
            instructionLabel.widthAnchor.constraint(lessThanOrEqualToConstant: 240),

            // Spinner + status row
            spinner.topAnchor.constraint(equalTo: instructionLabel.bottomAnchor, constant: 14),
            spinner.trailingAnchor.constraint(equalTo: view.centerXAnchor, constant: -4),
            spinner.centerYAnchor.constraint(equalTo: statusLabel.centerYAnchor),

            statusLabel.topAnchor.constraint(equalTo: instructionLabel.bottomAnchor, constant: 14),
            statusLabel.leadingAnchor.constraint(equalTo: view.centerXAnchor, constant: 4),

            // Countdown
            countdownLabel.topAnchor.constraint(equalTo: statusLabel.bottomAnchor, constant: 8),
            countdownLabel.centerXAnchor.constraint(equalTo: view.centerXAnchor),

            // Refresh button
            refreshBtn.topAnchor.constraint(equalTo: countdownLabel.bottomAnchor, constant: 16),
            refreshBtn.centerXAnchor.constraint(equalTo: view.centerXAnchor),
        ])
    }

    // -------------------------------------------------------------------------
    // Pairing session management
    // -------------------------------------------------------------------------

    /// Generates a new PairingSessionToken, renders its QR, and starts the
    /// expiry countdown. Any previously running timer is cancelled first.
    /// Per §QR Expiration: "Generating a new QR invalidates every previous
    /// unused QR." (Phase 12.2 enforces this on the backend.)
    private func startNewPairingSession() {
        stopTimer()

        let token = PairingSessionToken.generate()
        currentToken = token

        // Generate QR from JSON payload
        if let json = token.jsonString(),
           let qrImage = QRCodeGenerator.generate(from: json, size: 190) {
            qrImageView?.image = qrImage
        }

        // Start handshake controller
        stateObservationTask?.cancel()
        Task { await pairingController?.cancel(reason: "replaced") }
        
        let controller = PairingHandshakeController(token: token)
        pairingController = controller
        
        stateObservationTask = Task { [weak self] in
            for await state in controller.stateStream {
                guard let self else { return }
                if Task.isCancelled { break }
                self.updateUI(for: state)
            }
        }
        
        Task { await controller.start() }

        // Update countdown immediately, then every second
        updateCountdownDisplay()
        spinner?.startAnimation(nil)

        countdownTimer = Timer.scheduledTimer(
            withTimeInterval: 1.0, repeats: true
        ) { [weak self] _ in
            Task { @MainActor [weak self] in
                self?.tick()
            }
        }
    }

    /// Called every second by the countdown timer.
    private func tick() {
        guard let token = currentToken else { return }

        if token.isExpired {
            // Auto-regenerate when the QR expires (per user requirement).
            startNewPairingSession()
        } else {
            updateCountdownDisplay()
        }
    }

    private func updateCountdownDisplay() {
        guard let token = currentToken else { return }
        let secs = max(0, token.secondsRemaining)
        let m = secs / 60
        let s = secs % 60
        countdownLabel?.stringValue = String(format: "Expires in %d:%02d", m, s)
    }

    private func stopTimer() {
        countdownTimer?.invalidate()
        countdownTimer = nil
    }

    private func updateUI(for state: MacPairingState) {
        statusLabel?.stringValue = state.displayText
        
        switch state {
        case .secureChannelReady:
            spinner?.stopAnimation(nil)
            spinner?.isHidden = true
            statusLabel?.textColor = NSColor.systemGreen
            // Phase 12.3: Transition to trust establishment
        case .failed:
            spinner?.stopAnimation(nil)
            spinner?.isHidden = true
            statusLabel?.textColor = NSColor.systemRed
        default:
            spinner?.isHidden = false
            spinner?.startAnimation(nil)
            statusLabel?.textColor = .secondaryLabelColor
        }
    }

    // -------------------------------------------------------------------------
    // Actions
    // -------------------------------------------------------------------------

    @objc private func regenerateManually() {
        startNewPairingSession()
    }

    @objc private func goBack() {
        stateObservationTask?.cancel()
        Task { await pairingController?.cancel(reason: "user_cancelled") }
        navigationController?.pop()
    }

    // -------------------------------------------------------------------------
    // Page header factory
    // -------------------------------------------------------------------------

    private func makePageHeader(title: String) -> NSView {
        let container = NSView()
        container.translatesAutoresizingMaskIntoConstraints = false

        // Back button
        let backCfg = NSImage.SymbolConfiguration(pointSize: 13, weight: .semibold)
        let chevronImg = NSImage(systemSymbolName: "chevron.left",
                                 accessibilityDescription: "Back")?
            .withSymbolConfiguration(backCfg)

        let backBtn = NSButton(title: "", target: self, action: #selector(goBack))
        backBtn.isBordered = false
        backBtn.image = chevronImg
        backBtn.imagePosition = .imageLeading

        // Tint chevron image blue via SymbolConfiguration palette (macOS 12+)
        if #available(macOS 12, *) {
            let colourCfg = NSImage.SymbolConfiguration(paletteColors: [.systemBlue])
            backBtn.image = chevronImg?.withSymbolConfiguration(colourCfg)
        }

        let backAttr: [NSAttributedString.Key: Any] = [
            .foregroundColor: NSColor.systemBlue,
            .font: NSFont.systemFont(ofSize: 14, weight: .regular),
        ]
        backBtn.attributedTitle = NSAttributedString(string: " Back", attributes: backAttr)
        backBtn.translatesAutoresizingMaskIntoConstraints = false

        // Page title
        let titleLabel = NSTextField(labelWithString: title)
        titleLabel.font = .systemFont(ofSize: 15, weight: .semibold)
        titleLabel.textColor = .labelColor
        titleLabel.alignment = .center
        titleLabel.translatesAutoresizingMaskIntoConstraints = false

        container.addSubview(backBtn)
        container.addSubview(titleLabel)

        NSLayoutConstraint.activate([
            backBtn.leadingAnchor.constraint(equalTo: container.leadingAnchor, constant: 10),
            backBtn.centerYAnchor.constraint(equalTo: container.centerYAnchor),

            titleLabel.centerXAnchor.constraint(equalTo: container.centerXAnchor),
            titleLabel.centerYAnchor.constraint(equalTo: container.centerYAnchor),
        ])
        return container
    }

    private func makeSeparator() -> NSView {
        let box = NSBox()
        box.boxType = .separator
        box.translatesAutoresizingMaskIntoConstraints = false
        return box
    }
}
